beewebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Blog

info_dict = {
    'queryset': Blog.objects.all(),
    'data_field': 'update_time'
}

urlpatterns = [
    path('', views.home, name='home'),
    # path('', views.home, namespace='home'),  实例命名空间，   include使用namespace必须在app——name 下使用
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('accounts/', include('allauth.urls')),  # django-allauth第三方包登陆
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),  # 加载图片路由
    path('blog/', include('blog.urls')),  # 博客路由分发
    path('comment/', include('comment.urls')),  # 评论路由分发
    path('login/', include('login.urls')),  # 登录注册路由分发
    path('likes/', include('likes.urls')),  # 点赞路由分发
    path('my_notifications/', include('my_notifications.urls')),  # 站内提醒分发
    path('notifications/', include('notifications.urls', namespace='notifications')),  # 站内提醒通知
    # path('search/', views.search, name='search') # 自己的分词查询
    path('search/', include('haystack.urls', )),  # 全文检索
    path('sitemap.xml', sitemap, {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
         name='django.contrib.sitemaps.views.sitemap'),  # 生成sitemap
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from .feeds import ALLBlogRssFeed

# 应用命名空间
app_name = 'blog'
urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:blog_pk>', views.blog_detail, name='blog_detail'),
    path('type/<int:blog_type_pk>', views.blogs_with_type, name='blogs_with_type'),
    path('date/<int:year>/<int:month>', views.blogs_with_date, name='blogs_with_date'),
    path('tag/<int:blog_tag_pk>', views.blogs_with_tag, name='blogs_with_tag'),
    path('rss/', ALLBlogRssFeed(), name='rss'),  # RSS订阅
]

my_notifications/urls.py
from django.urls import path
from . import views

app_name = 'my_notifications'
urlpatterns =[
    path('', views.my_notifications, name='my_notifications'),
    path('<int:my_notification_pk>', views.my_notification, name='my_notification'),
    path('delete_my_read_notification/', views.delete_my_read_notifications, name='delete_my_read_notifications'),
]

my_notifications/views.py
from django.shortcuts import render, redirect, get_object_or_404
from notifications.models import Notification
from django.urls import reverse


def my_notifications(request):
    context = {}
    return render(request, 'my_notifications/my_notifications.html')


def my_notification(request, my_notification_pk):
    my_notification = get_object_or_404(Notification, pk=my_notification_pk)
    my_notification.unread = False
    my_notification.save()
    return redirect(my_notification.data['url'])


def delete_my_read_notifications(request):
    notifications = request.user.notifications.read()
    notifications.delete()
    return redirect(reverse('my_notifications:my_notifications'))

my_notifications/templates/my_notifications/my_notifications.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    我的网站|我的消息
{% endblock %}

{% block header_extends %}
    <link rel="stylesheet" href="{% static 'my_notifications/my_notifications.css' %}">
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <a href="{% url 'notifications:mark_all_as_read' %}?next={% url 'my_notifications:my_notifications' %}" class="btn btn-primary">全部标记为已读</a>
                <a href="{% url 'my_notifications:delete_my_read_notifications' %}" class="btn btn-danger">删除已读消息</a>
            <ul class="notifications">
                {% for notification in request.user.notifications.all %}

                    <li class="{% if not notification.unread %}read{% endif %}">
                        [{{ notification.timesince }}之前]
                        <a href="{% url 'my_notifications:my_notification' notification.pk %}">{{ notification.verb }}</a>
                    </li>
                {% empty %}
                    <li>暂无消息</li>
                {% endfor %}
            </ul>

            </div>
        </div>
    </div>

{% endblock %}