beewebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Blog

info_dict = {
    'queryset': Blog.objects.all(),
    'data_field': 'update_time'
}

urlpatterns = [
    path('', views.home, name='home'),
    # path('', views.home, namespace='home'),  实例命名空间，   include使用namespace必须在app——name 下使用
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('accounts/', include('allauth.urls')),  # django-allauth第三方包登陆
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),  # 加载图片路由
    path('blog/', include('blog.urls')),  # 博客路由分发
    path('comment/', include('comment.urls')),  # 评论路由分发
    path('login/', include('login.urls')),  # 登录注册路由分发
    path('likes/', include('likes.urls')),  # 点赞路由分发
    path('my_notifications/', include('my_notifications.urls')),  # 站内提醒分发
    path('notifications/', include('notifications.urls', namespace='notifications')),  # 站内提醒通知
    # path('search/', views.search, name='search') # 自己的分词查询
    path('search/', include('haystack.urls', )),  # 全文检索
    path('sitemap.xml', sitemap, {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
         name='django.contrib.sitemaps.views.sitemap'),  # 生成sitemap
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from .feeds import ALLBlogRssFeed

# 应用命名空间
app_name = 'blog'
urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:blog_pk>', views.blog_detail, name='blog_detail'),
    path('type/<int:blog_type_pk>', views.blogs_with_type, name='blogs_with_type'),
    path('date/<int:year>/<int:month>', views.blogs_with_date, name='blogs_with_date'),
    path('tag/<int:blog_tag_pk>', views.blogs_with_tag, name='blogs_with_tag'),
    path('rss/', ALLBlogRssFeed(), name='rss'),  # RSS订阅
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path("", views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('user_info/', views.user_info, name='user_info'),
    path('change_nickname/', views.change_nickname, name='change_nickname'),
    path('bind_email/', views.bind_email, name='bind_email'),
    path('send_email_code/',views.send_verification_code, name='send_email_code'),
    path('change_password/', views.change_password, name='change_password'),
    path('forget_password/', views.forget_password, name='forget_password'),
    path('login_by_qq',views.login_by_qq, name='login_by_qq'), # hwjbee.fun/login/login_by_qq
    path('login_by_weixin', views.login_by_weixin, name='login_by_weixin'),  # hwjbee.fun/login/login_by_weixin
    path('bind_qq', views.bind_qq, name='bind_qq'),
    path('create_user_by_qq', views.create_user_by_qq, name='create_user_by_qq')

]

login/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class OAuthRelationship(models.Model):
    OAUTH_TYPE_CHOICES = (
        (0, 'QQ'),
        (1, 'WeChat'),
        (2, 'Sina'),
        (3, 'Github'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    openid = models.CharField(max_length=128)
    oauth_type = models.IntegerField(choices=OAUTH_TYPE_CHOICES, default=0, verbose_name='第三方登录方式')

    def __str__(self):
        return 'OAuthRelationship:%s' % self.user.username

    class Meta:
        verbose_name = '第三方账号关系'
        verbose_name_plural = verbose_name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=24, verbose_name='昵称')

    def __str__(self):
        return '<Profile: %s for %s>' % (self.nickname, self.user)

    class Meta:
        verbose_name = '用户拓展信息'
        verbose_name_plural = '用户拓展信息'


def get_nickname(self):
    if Profile.objects.filter(user=self).exists():
        profile = Profile.objects.get(user=self)
        return profile.nickname
    else:
        return ''


def has_nickname(self):
    return Profile.objects.filter(user=self).exists()


def get_nickname_or_username(self):
    if Profile.objects.filter(user=self).exists():
        profile = Profile.objects.get(user=self)
        return profile.nickname
    else:
        return self.username


User.get_nickname = get_nickname
User.has_nickname = has_nickname
User.get_nickname_or_username = get_nickname_or_username

login/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from .models import OAuthRelationship


class LoginForm(forms.Form):
    username_or_email = forms.CharField(label='用户名或邮箱',
                                        widget=forms.TextInput(
                                            attrs={'class': 'form-control', 'placeholder': '请输入用户名或邮箱'}))
    password = forms.CharField(label='密码',
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入用密码'}))

    def clean(self):
        username_or_email = self.cleaned_data.get('username_or_email')
        password = self.cleaned_data.get('password')

        user = auth.authenticate(username=username_or_email, password=password)
        if user is None:
            if User.objects.filter(email=username_or_email).exists():
                username = User.objects.get(email=username_or_email).username
                user = auth.authenticate(username=username, password=password)
                if user is None:
                    raise forms.ValidationError('用户名或密码不正确')
                else:
                    self.cleaned_data['user'] = user
            else:
                raise forms.ValidationError('用户名或密码不正确')
        else:
            self.cleaned_data['user'] = user
        return self.cleaned_data


class RegForm(forms.Form):
    username = forms.CharField(label='用户名',
                               max_length=30,
                               min_length=3,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入3-30位用户名'}))
    email = forms.EmailField(label='邮箱',
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': '请输入邮箱'}))
    verification_code = forms.CharField(label='验证码',
                                        required=False,
                                        widget=forms.TextInput(
                                            attrs={'class': 'form-control', 'placeholder': '点击发送验证码'}))
    password = forms.CharField(label='密码',
                               min_length=6,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入密码'}))
    password_again = forms.CharField(label='重复密码',
                                     min_length=6,
                                     widget=forms.PasswordInput(
                                         attrs={'class': 'form-control', 'placeholder': '请再次输入密码'}))

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(RegForm, self).__init__(*args, **kwargs)

    def clean(self):
        code = self.request.session.get('register_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')
        return self.cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('用户名已存在')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱已存在')
        return email

    def clean_password_again(self):
        password = self.cleaned_data.get('password')
        password_again = self.cleaned_data.get("password_again")
        if password != password_again:
            raise forms.ValidationError('两次密码输入不一致')
        return password_again

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get('verification_code')
        if verification_code == '':
            raise forms.ValidationError('验证码不能为空')
        return verification_code


class ChangeNicknameForm(forms.Form):
    nickname_new = forms.CharField(
        label='新的昵称',
        max_length=20,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '请输入新的昵称'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangeNicknameForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登录
        if self.user.is_authenticated:
            self.cleaned_data['user'] = self.user
        else:
            raise forms.ValidationError('用户尚未登录')
        return self.cleaned_data

    def clean_nickname_new(self):
        nickname_new = self.cleaned_data.get('nickname_new', '').strip()
        if nickname_new == '':
            raise forms.ValidationError("新的昵称不能为空")
        return nickname_new


class BindEmailForm(forms.Form):
    email = forms.EmailField(label='邮箱',
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': '请输入邮箱'}))
    verification_code = forms.CharField(label='验证码',
                                        required=False,
                                        widget=forms.TextInput(
                                            attrs={'class': 'form-control', 'placeholder': '点击发送验证码'}))

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(BindEmailForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 用户是否登录
        if self.request.user.is_authenticated:
            self.cleaned_data['user'] = self.request.user
        else:
            raise forms.ValidationError('用户尚未登录')
        # 用户是否绑定
        if self.request.user.email != '':
            raise forms.ValidationError('你已经绑定邮箱')
        # 判断验证码
        code = self.request.session.get('bind_email_code')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')
        return self.cleaned_data

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get('verification_code')
        if verification_code == '':
            raise forms.ValidationError('验证码不能为空')
        return verification_code

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('该邮箱已经绑定')
        return email


class ChangePasswordForm(forms.Form):
    password_old = forms.CharField(label='旧密码',
                                   min_length=6,
                                   widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入旧密码'}))
    password_new = forms.CharField(label='新密码',
                                   min_length=6,
                                   widget=forms.PasswordInput(
                                       attrs={'class': 'form-control', 'placeholder': '请输入新密码'}))
    password_new_again = forms.CharField(label='重复新密码',
                                         min_length=6,
                                         widget=forms.PasswordInput(
                                             attrs={'class': 'form-control', 'placeholder': '请重复输入新密码'}))

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登录,
        if self.user.is_authenticated:
            self.cleaned_data['user'] = self.user
        else:
            raise forms.ValidationError('用户尚未登录')
        return self.cleaned_data

    def clean_password_old(self):
        password_old = self.cleaned_data.get('password_old')
        if not self.user.check_password(password_old):
            raise forms.ValidationError("原先密码错误")
        return password_old

    def clean_password_new_again(self):
        password_new = self.cleaned_data.get('password_new', '')
        password_new_again = self.cleaned_data.get("password_new_again", '')
        if password_new != password_new_again or password_new == '':
            raise forms.ValidationError('两次密码输入不一致')
        return self.cleaned_data


class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(label='邮箱',
                             widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入用户名邮箱'}))

    password_new = forms.CharField(label='新密码',
                                   min_length=6,
                                   widget=forms.PasswordInput(
                                       attrs={'class': 'form-control', 'placeholder': '请再次输入密码'}))
    verification_code = forms.CharField(label='验证码',
                                        required=False,
                                        widget=forms.TextInput(
                                            attrs={'class': 'form-control', 'placeholder': '点击发送验证码'}))

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(ForgotPasswordForm, self).__init__(*args, **kwargs)

    def clean_username(self):
        email = self.cleaned_data.get('email').strip()
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError('不存在该邮箱')
        return email

    def clean_verification_code(self):
        code = self.request.session.get('forget_password_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if verification_code == '':
            raise forms.ValidationError('验证码不能为空')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')
        return verification_code


class BindQQForm(forms.Form):
    username_or_email = forms.CharField(label='用户名或邮箱',
                                        widget=forms.TextInput(

login/templates/login/bind_email_form.html
{% extends 'form.html' %}
{% block other_buttons %}

    <button id='send_code' class="btn btn-primary">发送验证码</button>
{% endblock %}
{% block script_extends %}
    <script type="text/javascript">
        $("#send_code").click(function () {
           var email = $('#id_email').val();
           if (email==''){
               $('#tip').text('*邮箱不能为空*');
               return false;
           }
           // 发送验证码
           $.ajax({
               url:"{% url 'login:send_email_code' %}",
               type:"GET",
               data:{
                   'email':email,
                   'send_for':'bing_email_code',
               },
               cache:false,
               success:function (data) {
                   if(data['status']=='ERROR') {
                       alert(data['status']);
                   }
               }
           });
           // 把按钮变灰
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 30;
            $(this).text(time+'s');
            var interval = setInterval(()=> {
                if(time<=0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }
                time --;
                $(this).text(time+'s');
            },1000);
        })
    </script>
{% endblock %}

login/templates/login/forget_password.html
{% extends 'form.html' %}

{% block other_buttons %}
    <button id='send_code' class="btn btn-primary">发送验证码</button>
{% endblock %}
{% block script_extends %}
    <script type="text/javascript">
        $("#send_code").click(function () {
           var email = $('#id_email').val();
           if (email==''){
               $('#tip').text('*邮箱不能为空*');
               return false;
           }
           // 发送验证码
           $.ajax({
               url:"{% url 'login:send_email_code' %}",
               type:"GET",
               data:{
                   'email':email,
                   'send_for':'forget_password_code',
               },
               cache:false,
               success:function (data) {
                   if(data['status']=='ERROR') {
                       alert(data['status']);
                   }
               }
           });
           // 把按钮变灰
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 30;
            $(this).text(time+'s')
            var interval = setInterval(()=> {
                if(time<=0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }
                time --;
                $(this).text(time+'s');
            },1000);
        })
    </script>
{% endblock %}

login/templates/login/login.html
{% extends 'base.html' %}
{% load static %}
{% load login_tags %}

{% block title %}
    我的网站|登录
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">登录</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in login_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {% if field.id_for_label == 'id_password' %}

                                        <a href="{% url 'login:forget_password' %}">(忘记密码?)</a>
                                    {% endif %}
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span id="tip" class="pull-left text-danger">{{ login_form.non_field_errors }}</span>
                                <div class="clearfix"></div>
                                <div style="margin: 6px; display: inline-block">
                                    <a href="{% get_login_weibo_url %}">
                                        <img src="{% static 'login/images/weibo.png' %}">
                                        微博
                                    </a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href="{% get_login_qq_url %}">
                                        <img src="{% static 'login/images/qq.jpg' %}">
                                        QQ
                                    </a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href="{% get_login_weixin_url %}">
                                        <img src="{% static 'login/images/weixin.png' %}">
                                        微信
                                    </a>

                                </div>
                                <input type="submit" value="登录" class="btn btn-primary pull-right">
                            </form>
                        </div>
                    </div>
                    <div>
                        {% if request.GET.from %}
                            <a style="text-align: center; display: block;"
                               href="{% url 'login:register' %}?from={{ request.GET.from }}">前往注册&gt;&gt;</a>
                        {% else %}
                            <a style="text-align: center; display: block;"
                               href="{% url 'login:register' %}?from={{ request.get_full_path }}">前往注册&gt;&gt;</a>
                        {% endif %}
                    </div>
                {% else %}
                    <span>已登录，跳转到首页</span>
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

login/templates/login/login_by_qq.html
{% extends 'base.html' %}
{% load static %}
{% load login_tags %}

{% block title %}
    我的网站|绑定QQ
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div style="margin: 0 auto; text-align: center">
                        <img style="border-radius: 50%" src="{{ avatar }}">
                        <p>你好，{{ nickname }}</p>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">绑定用户</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in bind_qq_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <a href="{% url 'login:forget_password' %}" class="pull-left">忘记密码</a>
                                <span id="tip" class="pull-left text-danger">{{ bind_qq_form.non_field_errors }}</span>
                                <input type="submit" value="绑定" class="btn btn-primary pull-right">
                            </form>
                        </div>
                    </div>
                    <a style="text-align: center;display: block" href="{% url 'login:create_user_by_qq' %}?nickname={{ nickname }}">
                        没有账号？直接登录并创建账号&gt;&gt;
                    </a>

                {% else %}
                    <span>已登录，跳转到首页</span>
                    <script type="text/javascript">
                        window.location.href='/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>    
{% endblock %}

login/templates/login/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load login_tags %}

{% block title %}
    我的网站|注册
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div class="panel panel-default">
                        <div class="panel-heading">

                            <h3 class="panel-title">注册</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in reg_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {% if field.id_for_label == 'id_email' %}
                                        <div class="input-group">
                                            {{ field }}
                                            <span class="input-group-btn">
                                            <button id="send_code" class="btn btn-primary">发送验证码</button>
                                        </span>
                                        </div>

                                    {% else %}
                                        {{ field }}
                                    {% endif %}

                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span id="tip" class=" text-danger">{{ reg_form.non_field_errors }}</span>
                                <div class="clearfix"></div>
                                <div style="margin: 6px; display: inline-block">
                                    <a href="{% get_login_weibo_url %}">
                                        <img src="{% static 'login/images/weibo.png' %}">
                                        微博
                                    </a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href="{% get_login_qq_url %}">
                                        <img src="{% static 'login/images/qq.jpg' %}">
                                        QQ
                                    </a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href="{% get_login_weixin_url %}">
                                        <img src="{% static 'login/images/weixin.png' %}">
                                        微信
                                    </a>
                                </div>
                                <input type="submit" value="注册" class="btn btn-primary pull-right">
                            </form>
                        </div>
                    </div>
                    <div>
                        {% if request.GET.from %}
                            <a style="text-align: center; display: block;"
                               href="{% url 'login:login' %}?from={{ request.GET.from }}">前往登录&gt;&gt;</a>
                        {% else %}
                            <a style="text-align: center; display: block;"
                               href="{% url 'login:login' %}?from={{ request.get_full_path }}">前往登录&gt;&gt;</a>
                        {% endif %}
                    </div>
                {% else %}
                    <span>已登录，跳转到首页</span>
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block script_extends %}
    <script type="text/javascript">
        $("#send_code").click(function () {
            {#注意form表单自定义id#}
            var email = $('#id_email').val();
            {#alert(email)#}
            if (email == '') {
                $('#tip').text('*邮箱不能为空*');
                return false;
            }
            // 发送验证码
            $.ajax({
                url: "{% url 'login:send_email_code' %}",
                type: "GET",
                data: {
                    'email': email,
                    'send_for': 'register_code'
                },
                cache: false,
                success: function (data) {
                    if (data['status'] == 'ERROR') {
                        alert(data['status']);
                    }
                }
            });
            // 把按钮变灰
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 30;
            $(this).text(time + 's');
            var interval = setInterval(() => {
                if (time <= 0) {
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }
                time--;
                $(this).text(time + 's');
            }, 1000);
        })
    </script>
{% endblock %}

login/templates/login/user_info.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    个人资料
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                {% if user.is_authenticated %}
                    <h2>{{ user.username }}</h2>
                    <ul>
                        <li>昵称：{{ user.get_nickname }}<a href="{% url 'login:change_nickname' %}?from={{ request.get_full_path }}">(修改昵称)</a></li>
                        <li>邮箱：{% if user.email %}{{ user.email }}{% else %}暂无认证邮箱<a href="{% url 'login:bind_email' %}?from={{ request.get_full_path }}">绑定邮箱</a>{% endif %}</li>
                        <li>上一次登录的时间：{{ user.last_login|date:'Y-m-d H:i:s' }}</li>
                        <li><a href="{% url 'login:change_password' %}">(修改密码)</a></li>
                    </ul>
                {% else %}
                    <span>未登录，跳转到首页...</span>
                    <script type="text/javascript">
                        window.location.href='/';
                    </script>
                {% endif %}

            </div>
        </div>
    </div>    
{% endblock %}