beewebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Blog

info_dict = {
    'queryset': Blog.objects.all(),
    'data_field': 'update_time'
}

urlpatterns = [
    path('', views.home, name='home'),
    # path('', views.home, namespace='home'),  实例命名空间，   include使用namespace必须在app——name 下使用
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('accounts/', include('allauth.urls')),  # django-allauth第三方包登陆
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),  # 加载图片路由
    path('blog/', include('blog.urls')),  # 博客路由分发
    path('comment/', include('comment.urls')),  # 评论路由分发
    path('login/', include('login.urls')),  # 登录注册路由分发
    path('likes/', include('likes.urls')),  # 点赞路由分发
    path('my_notifications/', include('my_notifications.urls')),  # 站内提醒分发
    path('notifications/', include('notifications.urls', namespace='notifications')),  # 站内提醒通知
    # path('search/', views.search, name='search') # 自己的分词查询
    path('search/', include('haystack.urls', )),  # 全文检索
    path('sitemap.xml', sitemap, {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
         name='django.contrib.sitemaps.views.sitemap'),  # 生成sitemap
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from .feeds import ALLBlogRssFeed

# 应用命名空间
app_name = 'blog'
urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:blog_pk>', views.blog_detail, name='blog_detail'),
    path('type/<int:blog_type_pk>', views.blogs_with_type, name='blogs_with_type'),
    path('date/<int:year>/<int:month>', views.blogs_with_date, name='blogs_with_date'),
    path('tag/<int:blog_tag_pk>', views.blogs_with_tag, name='blogs_with_tag'),
    path('rss/', ALLBlogRssFeed(), name='rss'),  # RSS订阅
]

blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse

from read_statistics.models import ReadNumExpandMethod, ReadDetail


# Create your models here.
class BlogType(models.Model):
    type_name = models.CharField(max_length=64,verbose_name='博客类型')

    def __str__(self):
        return self.type_name

    class Meta:
        verbose_name = '博客类型'
        verbose_name_plural = verbose_name


class Tag(models.Model):
    name = models.CharField(max_length=16, verbose_name='标签名')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name


class Blog(models.Model, ReadNumExpandMethod):
    title = models.CharField(max_length=64,verbose_name='标题')
    content = RichTextUploadingField(verbose_name='内容')
    c_time = models.DateTimeField(auto_now_add=False,verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True,verbose_name='更新时间')
    read_detail = GenericRelation(ReadDetail,verbose_name='阅读详情')

    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')
    tags = models.ManyToManyField(Tag, blank=True)
    blog_type = models.ForeignKey(BlogType, on_delete=models.CASCADE, verbose_name='博客类型')

    def __str__(self):
        return self.title

    def get_user(self):
        return self.author

    def get_url(self):
        return reverse('blog:blog_detail', kwargs={'blog_pk': self.pk})

    def get_email(self):
        return self.author.email

    # 固定名称给rss使用
    def get_absolute_url(self):
        return reverse('blog:blog_detail', kwargs={'blog_pk': self.pk})

    class Meta:
        ordering = ['-c_time']
        verbose_name = '博客'
        verbose_name_plural = verbose_name

blog/views.py
import random
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.conf import settings
from django.db.models import Count

from .models import Blog, BlogType, Tag
from read_statistics.utils import read_statistics_once_read


# Create your views here.
def get_blog_list_common_data(request, blogs_all_list):
    paginator = Paginator(blogs_all_list, settings.EACH_PAGE_BLOGS_NUMBER)
    page_num = request.GET.get('page', 1)  # 获取url的页面请求,获取第几页
    page_of_blogs = paginator.get_page(page_num)  # 当前页的博客
    current_page_num = page_of_blogs.number  # 获取当前的页码
    # 获取前后各两页的页码范围
    page_range = list(range(max(current_page_num - 2, 1), current_page_num)) + \
                 list(range(current_page_num, min(current_page_num + 2, paginator.num_pages) + 1))
    # 加上省略号标记
    if page_range[0] - 1 >= 2:
        page_range.insert(0, '...')
    if paginator.num_pages - page_range[-1] >= 2:
        page_range.append('...')
    # 加上首页和尾页
    if page_range[0] != 1:
        page_range.insert(0, 1)
    if page_range[-1] != paginator.num_pages:
        page_range.append(paginator.num_pages)

    # 获取日期归档对应的博客数量
    blog_dates = Blog.objects.dates('c_time', 'month', order='DESC')
    blog_dates_dict = {}
    for blog_date in blog_dates:
        blog_count = Blog.objects.filter(c_time__year=blog_date.year,
                                         c_time__month=blog_date.month).count()
        blog_dates_dict[blog_date] = blog_count

    context = {}
    tags = Tag.objects.all()
    context['blog_tags'] = tags
    context['blogs'] = page_of_blogs.object_list  # 分页器的方法
    context['page_of_blogs'] = page_of_blogs
    context['page_range'] = page_range
    context['blog_types'] = BlogType.objects.annotate(blog_count=Count('blog'))
    context['blog_dates'] = blog_dates_dict
    context['color_int'] =  random.randint(100000,999999)
    return context


def blog_list(request):
    blogs_all_list = Blog.objects.all()
    context = get_blog_list_common_data(request, blogs_all_list)
    return render(request, 'blog/blog_list.html', context)


def blog_detail(request, blog_pk):
    blog = get_object_or_404(Blog, pk=blog_pk)
    read_cookie_key = read_statistics_once_read(request, blog)

    context = {}
    context['previous_blog'] = Blog.objects.filter(c_time__gt=blog.c_time).last()
    context['next_blog'] = Blog.objects.filter(c_time__lt=blog.c_time).first()
    context['blog'] = blog
    # 设置cookie
    response = render(request, 'blog/blog_detail.html', context)
    response.set_cookie(read_cookie_key, 'true', expires=60)
    return response


def blogs_with_date(request, year, month):
    blogs_all_list = Blog.objects.filter(c_time__month=month, c_time__year=year)
    context = get_blog_list_common_data(request, blogs_all_list)
    context['blogs_with_date'] = '%s年%s月' % (year, month)
    return render(request, 'blog/blogs_with_date.html', context)


def blogs_with_type(request, blog_type_pk):
    blog_type = get_object_or_404(BlogType, pk=blog_type_pk)
    blogs_all_list = Blog.objects.filter(blog_type=blog_type)
    context = get_blog_list_common_data(request, blogs_all_list)
    context['blog_type'] = blog_type
    return render(request, 'blog/blogs_with_type.html', context)

def blogs_with_tag(request, blog_tag_pk):
    blog_tag = get_object_or_404(Tag, pk=blog_tag_pk)
    blogs_all_list = Blog.objects.filter(tags=blog_tag)
    context = get_blog_list_common_data(request,blogs_all_list)
    context['blog_tag'] = blog_tag
    return render(request, 'blog/blogs_with_tag.html', context)

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% block title %}我的网站{% endblock %}
{% block nav_blog_active %}active{% endblock %}

{% load static %}
{% load comment_tags %}
{% load likes_tags %}

{% block header_extends %}
    <link rel="stylesheet" href="{% static 'blog/blog.css' %}">
{% endblock %}

{# 页面内容 #}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-9 col-lg-10">
                <div class="panel panel-default">
                    <div class="panel-heading">{% block blog_list_title %}博客列表{% endblock %}</div>
                    <div class="panel-body">
                        {% for blog in blogs %}
                            <div class="blog">
                                <h3><a href="{% url 'blog:blog_detail' blog.pk %}">{{ blog.title }}</a></h3>
                                <p class="blog-info">
                                    <span class="glyphicon glyphicon-tag"></span> <a
                                        href="{% url 'blog:blogs_with_type' blog.blog_type.pk %}">{{ blog.blog_type }}</a>&nbsp;&nbsp;
                                    <span class="glyphicon glyphicon-time"></span> {{ blog.c_time|date:"Y-m-d" }}&nbsp;&nbsp;
                                    阅读({{ blog.get_read_num }})&nbsp;&nbsp;
                                    评论({% get_comment_count blog %})&nbsp;&nbsp;
                                    点赞({% get_like_count blog %})
                                </p>
                                <p>{{ blog.content|striptags|truncatechars:120|safe }}</p>
                            </div>
                        {% empty %}
                            <div class="blog">
                                <h3>暂无博客，敬请期待</h3>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="paginator">
                    <ul class="pagination">
                        {# 上一页 #}
                        <li>
                            {% if page_of_blogs.has_previous %}
                                <a href="?page={{ page_of_blogs.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            {% else %}
                                <span aria-hidden="true">&laquo;</span>
                            {% endif %}
                        </li>
                        {# 全部页码 #}
                        {% for page_num in page_range %}
                            {% if page_num == page_of_blogs.number %}
                                <li class="active"><span>{{ page_num }}</span></li>
                            {% else %}
                                {% if page_num == '...' %}
                                    <li><span>{{ page_num }}</span></li>
                                {% else %}
                                    <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        {# 下一页 #}
                        <li>
                            {% if page_of_blogs.has_next %}
                                <a href="?page={{ page_of_blogs.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            {% else %}
                                <span aria-hidden="true">&raquo;</span>
                            {% endif %}
                        </li>
                    </ul>
                    <p>
                        共有{{ page_of_blogs.paginator.count }}篇博客，
                        当前第{{ page_of_blogs.number }}页，共{{ page_of_blogs.paginator.num_pages }}页
                    </p>
                </div>
            </div>
            <div class="hidden-xs col-sm-4 col-md-3 col-lg-2">
                <div class="panel panel-default">
                    <div class="panel-heading">博客分类</div>
                    <div class="panel-body">
                        <ul class="blog-types">
                            {% for blog_type in blog_types %}
                                <li style="margin-bottom: 2px;">
                                <span style="padding: 2px;">
                                    <a class="label {% cycle 'label-default' 'label-primary' 'label-success' 'label-info' 'label-warning' %}" href="{% url 'blog:blogs_with_type' blog_type.pk %}">
                                        {{ blog_type.type_name }} ({{ blog_type.blog_count }})
                                    </a>
                                </span>
                                </li>
                            {% empty %}
                                <li>暂无分类</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">日期归档</div>
                    <div class="panel-body">
                        <ul>
                            {% for blog_date, blog_count in blog_dates.items %}
                                <li style="padding: 2px; ">
                                    <a class="label {% cycle 'label-default' 'label-primary' 'label-success' 'label-info' 'label-warning' %}" href="{% url 'blog:blogs_with_date' blog_date.year blog_date.month %}">
                                        {{ blog_date|date:"Y年m月" }}({{ blog_count }})
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">标签云</div>
                    <div class="panel-body">
                        <ul>
                            {% for tag in blog_tags %}
                                <a href="{% url 'blog:blogs_with_tag' tag.pk %}">
                                    <span class="label {% cycle 'label-default' 'label-primary' 'label-success' 'label-info' 'label-warning' %}">{{ tag.name }}</span></a>
                            {% empty %}
                                暂无标签！
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div style="font-size: 20px; margin-left: 5px">
                    <a href="{% url 'blog:rss' %}"><span class="glyphicon glyphicon-hand-right"
                                                         aria-hidden="true"></span> RSS 订阅</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogs_with_date.html
{% extends 'blog/blog_list.html' %}
{% block title %}{{ blog_type.type_name }}{% endblock %}

{% block blog_list_title %}
    日期归档：{{ blogs_with_date }}
    <a href="{% url 'blog:blog_list' %}">查看全部博客</a>
{% endblock %}

blog/templates/blog/blogs_with_tag.html
{% extends 'blog/blog_list.html' %}
{% block title %}{{ blog_tag.name }}{% endblock %}

{% block blog_list_title %}
    标签：{{ blog_tag.name }}
    <a href="{% url 'blog:blog_list' %}">查看全部博客</a>
{% endblock %}

blog/templates/blog/blogs_with_type.html
{% extends 'blog/blog_list.html' %}
{% block title %}{{ blog_type.type_name }}{% endblock %}

{% block blog_list_title %}
    分类：{{ blog_type.type_name }}
    <a href="{% url 'blog:blog_list' %}">查看全部博客</a>
{% endblock %}