beewebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Blog

info_dict = {
    'queryset': Blog.objects.all(),
    'data_field': 'update_time'
}

urlpatterns = [
    path('', views.home, name='home'),
    # path('', views.home, namespace='home'),  实例命名空间，   include使用namespace必须在app——name 下使用
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('accounts/', include('allauth.urls')),  # django-allauth第三方包登陆
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),  # 加载图片路由
    path('blog/', include('blog.urls')),  # 博客路由分发
    path('comment/', include('comment.urls')),  # 评论路由分发
    path('login/', include('login.urls')),  # 登录注册路由分发
    path('likes/', include('likes.urls')),  # 点赞路由分发
    path('my_notifications/', include('my_notifications.urls')),  # 站内提醒分发
    path('notifications/', include('notifications.urls', namespace='notifications')),  # 站内提醒通知
    # path('search/', views.search, name='search') # 自己的分词查询
    path('search/', include('haystack.urls', )),  # 全文检索
    path('sitemap.xml', sitemap, {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
         name='django.contrib.sitemaps.views.sitemap'),  # 生成sitemap
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from .feeds import ALLBlogRssFeed

# 应用命名空间
app_name = 'blog'
urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:blog_pk>', views.blog_detail, name='blog_detail'),
    path('type/<int:blog_type_pk>', views.blogs_with_type, name='blogs_with_type'),
    path('date/<int:year>/<int:month>', views.blogs_with_date, name='blogs_with_date'),
    path('tag/<int:blog_tag_pk>', views.blogs_with_tag, name='blogs_with_tag'),
    path('rss/', ALLBlogRssFeed(), name='rss'),  # RSS订阅
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path("", views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('user_info/', views.user_info, name='user_info'),
    path('change_nickname/', views.change_nickname, name='change_nickname'),
    path('bind_email/', views.bind_email, name='bind_email'),
    path('send_email_code/',views.send_verification_code, name='send_email_code'),
    path('change_password/', views.change_password, name='change_password'),
    path('forget_password/', views.forget_password, name='forget_password'),
    path('login_by_qq',views.login_by_qq, name='login_by_qq'), # hwjbee.fun/login/login_by_qq
    path('login_by_weixin', views.login_by_weixin, name='login_by_weixin'),  # hwjbee.fun/login/login_by_weixin
    path('bind_qq', views.bind_qq, name='bind_qq'),
    path('create_user_by_qq', views.create_user_by_qq, name='create_user_by_qq')

]

my_notifications/urls.py
from django.urls import path
from . import views

app_name = 'my_notifications'
urlpatterns =[
    path('', views.my_notifications, name='my_notifications'),
    path('<int:my_notification_pk>', views.my_notification, name='my_notification'),
    path('delete_my_read_notification/', views.delete_my_read_notifications, name='delete_my_read_notifications'),
]

templates/about.html
{% extends 'base.html' %}
{% block title %}
    我的网站|关于
{% endblock %}
{% block nav_about_active %}active{% endblock %}
{% block header_extends %}
    <style type="text/css">
        p{
            text-indent: 2em;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <h3>Python （计算机程序设计语言）</h3>
        <h4>发展历程</h4>
        <p>从20世纪90年代初Python语言诞生至今，它已被逐渐广泛应用于系统管理任务的处理和Web编程。</p>
        <p>Python的创始人为荷兰人吉多·范罗苏姆  （Guido van Rossum）。自1989年圣诞节期间，在阿姆斯特丹，Guido为了打发圣诞节的无趣，决心开发一个新的脚本解释程序，作为ABC 语言的一种继承。之所以选中Python（大蟒蛇的意思）作为该编程语言的名字，是取自英国20世纪70年代首播的电视喜剧《蒙提.派森的飞行马戏团》（Monty Python's Flying Circus）。</p>
        <p>ABC是由Guido参加设计的一种教学语言。就Guido本人看来，ABC 这种语言非常优美和强大，是专门为非专业程序员设计的。但是ABC语言并没有成功，究其原因，Guido 认为是其非开放造成的。Guido 决心在Python 中避免这一错误。同时，他还想实现在ABC 中闪现过但未曾实现的东西。
就这样，Python在Guido手中诞生了。可以说，Python是从ABC发展起来，主要受到了Modula-3（另一种相当优美且强大的语言，为小型团体所设计的）的影响。并且结合了Unix shell和C的习惯。</p>
        <p>Python已经成为最受欢迎的程序设计语言之一。自从2004年以后，python的使用率呈线性增长。Python 2于2000年10月16日发布，稳定版本是Python 2.7。Python 3于2008年12月3日发布，不完全兼容Python 2。  2011年1月，它被TIOBE编程语言排行榜评为2010年度语言。</p>


        <p>由于Python语言的简洁性、易读性以及可扩展性，在国外用Python做科学计算的研究机构日益增多，一些知名大学已经采用Python来教授程序设计课程。例如卡耐基梅隆大学的编程基础、麻省理工学院的计算机科学及编程导论就使用Python语言讲授。众多开源的科学计算软件包都提供了Python的调用接口，例如著名的计算机视觉库OpenCV、三维可视化库VTK、医学图像处理库ITK。而Python专用的科学计算扩
展库就更多了，例如如下3个十分经典的科学计算扩展库：NumPy、SciPy和matplotlib，它们分别为Python提供了快速数组处理、数值运算以及绘图功能。因此Python语言及其众多的扩展库所构成的开发环境十分适合工程技术、科研人员处理实验数据、制作图表，甚至开发科学计算应用程序。2018年3月，该语言作者在邮件列表上宣布Python 2.7将于2020年1月1日终止支持。用户如果想要在这个日期之后继续得到与Python 2.7有关的支持，则需要付费给商业供应商。  </p>
    </div>


{% endblock %}

templates/base.html
{% load static %}
{% load notifications_tags %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'notifications/notify.js' %}"></script>
    {% block header_extends %}{% endblock %}
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'lufei2.jpeg' %}" class="img-responsive img-circle" style="margin: -8px 5px;"></a>
                <button class="navbar-toggle collapsed"  data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar-collapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="{% block nav_home_active %}{% endblock %}">
                        <a href="{% url 'home' %}">首页</a>
                    </li>
                    <li class="{% block nav_blog_active %}{% endblock %}">
                        <a href="{% url 'blog:blog_list' %}">博客</a>
                    </li>
                    <li class="{% block nav_about_active %}{% endblock %}">
                        <a href="{% url 'about' %}">关于</a>
                    </li>
                    <li class="{% block nav_contact_active %}{% endblock %}">
                        <a href="{% url 'contact' %}">联系</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <form role='search' class="navbar-form navbar-right search-form" action="{% url 'haystack_search' %}">
                            <div class="form-group">
                              <input type="text" class="form-control" name="q" placeholder="Search">
                            </div>
                            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                        </form>
                    </li>
                    {% if not user.is_authenticated %}
                        <li>
                            {% if request.GET.from %}
                                <a href="{% url 'login:login' %}">登录</a>
                                {% else %}
                                <a href="{% url 'login:login' %}?from={{ request.get_full_path }}">登录</a>
                            {% endif %}
                        </li>
                        <li>
                            {% if request.GET.from %}
                                <a href="{% url 'login:register' %}">注册</a>
                                {% else %}
                                <a href="{% url 'login:register' %}?from={{ request.get_full_path }}">注册</a>
                            {% endif %}
                        </li>
                        {% else %}
                        {% notifications_unread as unread_count %}
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">你好，{{ user.username }}
                              <span class="badge unread-count live_notify_badge">{% if unread_count > 0 %}{{ unread_count }}{% endif %}</span>

                              <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu">
                            <li><a href="{% url 'login:user_info' %}">个人资料</a></li>
                            <li><a href="{% url 'my_notifications:my_notifications' %}">我的消息 <span class="badge unread-count live_notify_badge">{% if unread_count > 0 %}{{ unread_count }}{% endif %}</span></a></li>
                            {% if user.is_staff or user.is_superuser %}
                                <li><a href="{% url 'admin:index' %}">后台管理</a></li>
                            {% endif %}
                            <li><a href="{% url 'login:logout' %}?from={{ request.get_full_path }}">退出</a></li>
{#                            <li role="separator" class="divider"></li>#}
                          </ul>
                        </li>
                    {% endif %}
                  </ul>
            </div>
        </div>
    </div>

    {% block content %}{% endblock %}

    <div class="footer">
        <div class="website-info">
            <p> <a href="http://www.hwjbee.fun">©2019 大哆哆个人博客网站</a> | 意见反馈或联系我（785216423@qq.com）</p>
        </div>
    </div>


    <script type="text/javascript">
        //底部栏置底
        //窗体改变大小事件
        $(window).resize(function(){
            //正文高度
            var body_height = $(document.body).outerHeight(true);

            //底部元素高度
            var bottom_height = $("#footer").outerHeight(true);

            //浏览器页面高度
            var window_height = $(window).height();

            //判断并调整底部元素的样式
            if($(".footer").hasClass('page-bottom')){
                //若包含有page-bottom类，就应用了position设置
                //当position为absolute时，body高度不包含这个元素
                //所以页面高度需要判断body和footer之和若小于浏览器窗口
                //则移除样式，让footer自然跟随在正文后面
                if(body_height + bottom_height >= window_height){
                    $(".footer").removeClass('page-bottom');
                }
            }else{
                //若没有page-bottom类，body高度包含footer
                //判断body高度小于浏览器时，则悬浮于底部
                if(body_height < window_height){
                    $(".footer").addClass('page-bottom');
                }
            }
        });

        //页面加载时，模拟触发一下resize事件
        $(window).trigger('resize');

        //自定义实时获取未读消息
        function my_special_notification_callback(data){
            unread_count = data['unread_count'];
            if (unread_count == 0) {
                unread_count = '';
            }
            $('.live_notify_badge').text(unread_count);
        }
</script>
    {% register_notify_callbacks callbacks='my_special_notification_callback' %}
{% block script_extends %}{% endblock %}
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% block title %}
    我的网站|联系
{% endblock %}
{% block nav_contact_active %}active{% endblock %}
{% block content %}
    <div class="container">
        <p>联系邮箱：785216423@qq.com/lantaiit@163.com</p>
    </div>
{% endblock %}

templates/error.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    我的网站|错误
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    {{ message }}，<a href="{{ redirect_to }}">返回</a>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ form_title }}</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                {% if not field.is_hidden %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                {% endif %}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span id="tip" class="pull-left text-danger">{{ form.non_field_errors }}</span>
                            <div class="clearfix"></div>
                            <div class="pull-left">
                                {% block other_buttons %}{% endblock %}
                            </div>
                            <div class="pull-right">
                                <input type="submit" value="{{ submit_text }}" class="btn btn-primary">
                                <button class="btn btn-default" onclick="window.location.href='{{ return_back_url }}'">返回</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    大哆哆博客|首页
{% endblock %}

{% block header_extends %}
    <link rel="stylesheet" href="{% static 'home.css' %}">
    <script src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <h3 class="home-content">欢迎访问大哆哆博客
        <a href="{% url 'blog:blog_list' %}">
            <span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>
        </a>
    </h3>
    <!-- 图表容器 DOM -->
    <div id="container"></div>
    <br>
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <div class="hot-data">
                <h3 class="text-danger">今天热门博客</h3>
                <ul>
                    {% for hot_data in today_hot_data %}
                        <li><a href="{% url 'blog:blog_detail' hot_data.content_object.pk %}">{{ hot_data.content_object.title }}</a>({{ hot_data.read_num }})</li>
                    {% empty %}
                        <li>今天暂时没有热门博客</li>
                    {% endfor %}
                </ul>
            </div>

        </div>
            <div class="col-md-3">
                <div class="hot-data">
                    <h3 class="text-success">昨天热门博客</h3>
                    <ul>
                        {% for hot_data in yesterday_hot_data %}
                            <li><a href="{% url 'blog:blog_detail' hot_data.content_object.pk %}">{{ hot_data.content_object.title }}</a>({{ hot_data.read_num }})</li>
                        {% empty %}
                            <li>昨天暂时没有热门博客</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <div class="hot-data">
                    <h3 class="text-warning">7天热门博客</h3>
                    <ul>
                        {% for hot_blog in hot_blogs_for_7_days %}
                            <li><a href="{% url 'blog:blog_detail' hot_blog.id %}">{{ hot_blog.title }}</a>({{ hot_blog.read_num_sum }})</li>
                        {% empty %}
                            <li>昨天暂时没有热门博客</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <div class="hot-data">
                    <h3 class="text-muted">30天热门博客</h3>
                    <ul>
                        {% for hot_blog in hot_blogs_for_30_days %}
                            <li><a href="{% url 'blog:blog_detail' hot_blog.id %}">{{ hot_blog.title }}</a>({{ hot_blog.read_num_sum }})</li>
                        {% empty %}
                            <li>昨天暂时没有热门博客</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script>
        // 图表配置
        var options = {
            chart: { type: 'line' },
            title: { text: null },
            xAxis: {
                categories: {{ dates|safe }},   // x 轴分类
                tickmarkPlacement: 'on',
                title: { text: '前7日阅读量变化'},
            },
            yAxis: {
                title: { text: null },
                labels:{ enabled: false },
                gridLineDashStyle: 'Dash',
            },
            series: [{                              // 数据列
                name: '阅读量',                     // 数据列名
                data: {{ read_nums }}               // 数据
            }],
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            legend: { enabled: false },
            credits: { enabled: false },
        };
        // 图表初始化函数
        var chart = Highcharts.chart('container', options);
    </script>

{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    我的网站|搜索
{% endblock %}

{% block header_extends %}

{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                {% if search_word == '' %}
                    <h3>你没有搜索任何内容</h3>
                    <p>你可以尝试输入点什么东西，例如：django</p>
                {% else %}
                    <h3>搜索"{{ search_word }}",找到{{ search_blogs_count }}个结果</h3>
                    <hr>
                    {% for blog in page_of_blogs %}
                        <a href="{% url 'blog:blog_detail' blog.pk %}">
                            <h4>{{ blog.title }}</h4>
                        </a>
                        <p>{{ blog.content|striptags|truncatechars_html:100 }}</p>
                    {% empty %}
                        <p>没有找到任何东西，换个关键词试试</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="row" style="display: flex; justify-content: center">
            {% if page_of_blogs.has_previous %}
                <a class="btn btn-default" href="{% url 'search' %}?wd={{ search_word }}&page={{ page_of_blogs.previous_page_number }}">上一页</a>
            {% endif %}
            &nbsp;&nbsp;
            {% if page_of_blogs.has_next %}
                <a class="btn btn-default" href="{% url 'search' %}?wd={{ search_word }}&page={{ page_of_blogs.next_page_number }}">下一页</a>
            {% endif %}
        </div>
    </div>
{% endblock %}